### ISSUE TITLE
No protocol value for rabbitmq-node port

### ISSUE THREAD

**Issue by viiicky** [xarg/rabbitmq-statefulset#3]
There is no protocol for port `25672` here: https://github.com/xarg/rabbitmq-statefulset/blob/ceeaea41521f529555872353f783c157a4ede115/charts/rabbitmq/templates/service.yaml#L17

And there are double protocol values for the port `4369`. Both as `TCP`.

Though this is obvious that the latter is a typo, I want to know if the former is intentional?
PS: I couldn't find any other way of commenting, thus creating the issue.

**Comment by xarg** [comment]
It's a typo. The protocol is not needed at all since TCP is the default.
